"""Runtime orchestration: normalized Postgres → recon → structured case.

RAG / LLM are intentionally not implemented. The case dict is the handoff
surface: facts already known to the backend must not be regenerated by an LLM.
"""

from __future__ import annotations

from backend.app.services.reconciliation.reconciliation_service import ReconciliationService

# Downstream contract (not executed here):
#   structured case → retrieve evidence (RAG) → explain (LLM)


class ReconciliationPipeline:
    def __init__(self, service: ReconciliationService | None = None) -> None:
        self.service = service or ReconciliationService()

    def run_case(
        self,
        source_type: str,
        source_id: str,
        include_ml: bool = True,
        include_exception: bool = True,
    ) -> dict:
        return self.service.run(
            source_type=source_type,
            source_id=source_id,
            include_ml=include_ml,
            include_exception=include_exception,
        )
